global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    tls_config:
      insecure_skip_verify: true
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets:
          - '172.19.22.91:9091'
  - job_name: node_exporter
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['172.19.22.91:9100','172.19.22.210:9100']
  - job_name: process_exporter
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['172.19.22.91:9256']

