apiVersion: 1

datasources:
  - name: myinfluxdb
    type: influxdb
    access: proxy
    database: k6
    orgId: 1
    url: http://influxdb:8086
    isDefault: true
  - name: prometheus-in-docker
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
    editable: false
